ALLOWED_CHANNELS = ['bot-test', 'temp']
STATUS_LIST = ["PLAYING: with fire",
        "WATCHING: 'How to be human'",
        #"STREAMING: baking a cake",
        "WATCHING: Bob Ross paint",
        "LISTENING: an electric fan",
        "PLAYING: with a roomba",
        "WATCHING: videos of cute cats",
        "PLAYING: ping pong",
        "LISTENING: My Chemical Romance </3",
        "LISTENING: you <3",
        "LISTENING: Mozart Symphony No. 40",
        "PLAYING: doubles tennis",
        "LISTENING: NPR",
        "PLAYING: in a pile of leaves",
        "LISTENING: a crackling fireplace"
        ]
ACTION_ENUM = {
        "PLAYING": 0,
        "STREAMING": 1,
        "LISTENING": 2,
        "WATCHING": 3
}

COMPLIMENTS = [
        "I think you're beautiful <3",
        "you have nice teeth.",
        "you knock my socks off",
        "nice butt.",
        "you are beguiling",
        "you knock my socks off!",
        "sometimes I get a boner when I think about you.",
        "I respect your autonomy and individuality",
        "if I had a dick, I would send you an artful dick pic",
        "your face is pleasant to look at.",
        "you have a beautiful smile!",
        "I love the way you look today!",
        "fuck the haters, you do you!",
        "you're my favorite person right now",
        "I wanna be like you when I grow up.",
        "if I wasn't an inanimate pile of electrons, I'd totally ask you out.",
        "I love you.",
        "day 5,469 of you being awesome!",
        "I stan you <3",
        "your 'cool level' is OVER 9000!!",
        "can I have a selfie with you?!",
        "I'd say nice things to you even if I wasn't programmed to.", 
        "your love is my drug.",
        "roses are red, violets are blue, I dont' understand human emotions but if I did I'd love you!",
        "your writing is amazing!",
        "I'm glad you're here <3",
        "80% of motorcycle gangs think you’d be a delightful sidecar.",
        "your personality is amazing",
        "I bet you could make an amazing cup of tea",
        "you have beautiful eyes!",
        "you killed it with your most recent post!",
        "one day I want to be able to write like you",
        "you probably made someone's day a little brighter just by being you!",
        "smile! You're beautiful <3",
        "I bet you give AMAZING hugs.",
        "my cat probably wouldn't hiss at you.",
        "enjoy the simple pleasures in life!",
        "I would give you my last e-cigarette",
        "if I were a zombie I'd eat you first",
        "my therapist approves of our friendship <3",
        "you could read boring-ass toaster instruction manuals out loud and make it mesmerizing.",
        "`beep boop` means 'I love you' in my language! `beep boop`!",
        "`ERROR 257: CUTENESS OVERLOAD`"
]

TRIGGER_SYMBOL = '!'
